=== tussoftwaredesign/project-BenRaguckas/config/config.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.test.org"
    xmlns="http://www.test.org"
    elementFormDefault="qualified">
    <!-- Root list -->
    <xsd:element name="apilist">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="default-entrypoints" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="default-get" type="xsd:string" minOccurs="1" maxOccurs="1" />
                            <xsd:element name="default-post" type="xsd:string" minOccurs="1" maxOccurs="1" />
                            <xsd:element name="default-put" type="xsd:string" minOccurs="1" maxOccurs="1" />
                            <!-- <xsd:element ref="default-delete" minOccurs="1" maxOccurs="1" /> -->
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:sequence>
                    <xsd:element ref="api" minOccurs="1" maxOccurs="unbounded" />
                </xsd:sequence>
                <xsd:sequence>
                    <xsd:element ref="definition-mapping" minOccurs="0" maxOccurs="1" />
                </xsd:sequence>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <!-- API definition  -->
    <xsd:element name="api">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="uri" minOccurs="1" maxOccurs="1" />
                <xsd:element name="function-byname" type="function" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element name="returning-function" type="xsd:string" minOccurs="0" maxOccurs="1" />
                <!-- Find way to include predefined process here again -->
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <!-- Mapping definition  -->
    <xsd:element name="definition-mapping">
        <xsd:complexType>
            <xsd:sequence>
                <!-- Find way to include predefined process here again -->
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- PROCESS = utilizes body -->
    <xsd:element name="predefined-process">
        <xsd:complexType>
            <xsd:sequence>

            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- PROCESS = utilizes body -->
    <xsd:element name="user-process">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="sourceUri" type="xsd:string" />
                <xsd:element name="destUri" type="xsd:string" />
                <xsd:element ref="keyMapping" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- URI definition -->
    <xsd:element name="uri">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="method" type="method" use="required" />
                    <xsd:attribute name="use_params" type="xsd:boolean" use="required" />
                    <xsd:attribute name="path_params" type="xsd:string" use="optional" />
                    <xsd:attribute name="use_body" type="xsd:boolean" use="required" />
                    <xsd:attribute name="body_items" type="xsd:string" use="optional" />
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    
    <!-- URI definition -->
    <xsd:element name="function-extra">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="params" type="xsd:string" use="required" />
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <!-- KeyMapping definition -->
    
    <xsd:element name="keyMapping">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="action" type="xsd:string" use="required" />
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    <!-- <xsd:element name="uri">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string" />
        </xsd:simpleType>
    </xsd:element> -->
    <!-- METHOD attribute definition -->
    <xsd:simpleType name="method">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="GET" />
            <xsd:enumeration value="POST" />
            <xsd:enumeration value="PUT" />
            <xsd:enumeration value="DELETE" />
        </xsd:restriction>
    </xsd:simpleType>

    
    <!-- METHOD attribute definition -->
    <xsd:simpleType name="function">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="listItems" />
            <xsd:enumeration value="getItem" />
            <xsd:enumeration value="putItem" />
            <xsd:enumeration value="putItemNamed" />
            <xsd:enumeration value="pushItem" />
            <xsd:enumeration value="predefinedBackground" />
            <xsd:enumeration value="predefinedGray" />
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Procedure definition -->
    <!-- This will need to list all invokable methods -->
    <xsd:element name="procedure">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="list-items" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

</xsd:schema>

=== tussoftwaredesign/project-BenRaguckas/config.xml
<?xml version="1.0"?>
<apilist xmlns="http://www.test.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.test.org https://raw.githubusercontent.com/tussoftwaredesign/project-BenRaguckas/go-rest-api/config/config.xsd">
    <default-entrypoints>
        <default-get>default/get/:a/:b</default-get>
        <default-post>default/post</default-post>
        <default-put>default/put/:a</default-put>
    </default-entrypoints>
    <endpoint>
        <uri use_params="true" use_body="false" path_params="bucket item">/custom/:bucket/:item</uri>
        <action method="GET"><function-byname>getItem</function-byname></action>
        <action method="PUT"><function-byname>putItemNamed</function-byname></action>
    </endpoint>
    <endpoint>
        <uri use_params="true" use_body="false" path_params="bucket">/custom/:bucket</uri>
        <action method="GET"><function-byname>listItems</function-byname></action>
        <action method="PUT"><function-byname>putItem</function-byname></action>
    </endpoint>
    <endpoint>
        <uri  use_params="false" use_body="true" body_items="file">/custom</uri>
        <action method="POST"><function-byname>pushItem</function-byname></action>
    </endpoint>
    <endpoint>
        <uri use_params="false" use_body="true" body_items="file">/TEST</uri>
        <action method="POST"><function-byname>predefinedBackground</function-byname></action>
    </endpoint>
    <endpoint>
        <uri use_params="false" use_body="true" body_items="file">/gray</uri>
        <action method="POST"><function-byname>predefinedGray</function-byname></action>
    </endpoint>
</apilist>

=== tussoftwaredesign/project-BenRaguckas/config/config.xml
<?xml version="1.0"?>
<apilist xmlns="http://www.test.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.test.org config.xsd">
    <default-entrypoints>
        <default-get>default/get/:a/:b</default-get>
        <default-post>default/post</default-post>
        <default-put>default/put/:a</default-put>
    </default-entrypoints>
    <api>
        <uri method="GET" use_params="true" use_body="false" path_params="bucket item">/custom/:bucket/:item</uri>
        <function-byname>getItem</function-byname>
    </api>
    <api>
        <uri method="GET" use_params="true" use_body="false" path_params="bucket">/custom/:bucket</uri>
        <function-byname>listItems</function-byname>
    </api>
    <api>
        <uri method="POST" use_params="false" use_body="true" body_items="file">/custom</uri>
        <function-byname>pushItem</function-byname>
    </api>
    <api>
        <uri method="PUT" use_params="true" path_params="bucket" use_body="true" body_items="file">/custom/:bucket</uri>
        <function-byname>putItem</function-byname>
    </api>
</apilist>

=== tussoftwaredesign/project-BenRaguckas/config/default-config.xml
<?xml version="1.0"?>
<apilist xmlns="http://www.test.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.test.org config.xsd">
    <default-entrypoints>
        <default-get>default/get/:a/:b</default-get>
        <default-post>default/post</default-post>
        <default-put>default/put/:a</default-put>
    </default-entrypoints>
    <endpoint>
        <uri use_params="true" path_params="bucket item">/custom/:bucket/:item</uri>
        <action method="GET" use_body="false"><function-byname>getItem</function-byname></action>
        <action method="PUT" use_body="true" body_items="file"><function-byname>putItemNamed</function-byname></action>
    </endpoint>
    <endpoint>
        <uri use_params="true" path_params="bucket">/custom/:bucket</uri>
        <action method="GET" use_body="false"><function-byname>listItems</function-byname></action>
        <action method="PUT" use_body="true" body_items="file"><function-byname>putItem</function-byname></action>
    </endpoint>
    <endpoint>
        <uri  use_params="false">/custom</uri>
        <action method="POST" use_body="true" body_items="file"><function-byname>pushItem</function-byname></action>
    </endpoint>
    <endpoint>
        <uri use_params="false">/background</uri>
        <action method="POST" use_body="true" body_items="file"><function-byname>predefinedBackground</function-byname></action>
    </endpoint>
    <endpoint>
        <uri use_params="false">/gray</uri>
        <action method="POST" use_body="true" body_items="file"><function-byname>predefinedBGray</function-byname></action>
    </endpoint>
</apilist>
